# Generated by Django 2.2 on 2020-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsalApp', '0002_auto_20200418_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futsal',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
