# Generated by Django 2.2 on 2020-04-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsalApp', '0003_auto_20200418_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
