# Generated by Django 2.2.13 on 2020-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='futsalApp.Futsal'),
        ),
    ]
