# Generated by Django 2.2 on 2020-04-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_valid',
        ),
    ]
