# Generated by Django 2.2 on 2020-04-16 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 16, 11, 35, 38, 275322, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
